services:
  test:
    container_name: test-4
    build: .
    volumes:
      - .:/app
    command: pytest -s -v
  app:
    container_name: app-4
    build: .
    volumes:
      - .:/app
    depends_on:
      - test
    command: python3 main.py