services:
  test:
    container_name: test-3
    build: .
    volumes:
      - .:/app
    command: pytest -s -v
  app:
    container_name: app-3
    build: .
    volumes:
      - .:/app
      - ${USERPROFILE}/.aws:/root/.aws
    depends_on:
      - test
    command: python3 main.py